name: Build Next.js web application
on: push
jobs:
  build-project:
    name: Build Next.js project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: Upload site content
        uses: actions/upload-artifact@v2
        with:
          name: site-build
          path: .next/
  distribute-project:
    name: Distribute Next.js project to GitHub Releases
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: site-build
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1
          release_name: Release One